# Generated by Django 5.0.14 on 2026-02-14 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectinvitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectInvitation',
        ),
    ]
