import workspace_img_default from "./workspace_img_default.png";
import profile_img_a from "./profile_img_a.jpg";
import profile_img_o from "./profile_img_o.svg";
import profile_img_j from "./profile_img_j.svg";

export const assets = {
  workspace_img_default,
  profile_img_a,
  profile_img_o,
  profile_img_j,
};

export const dummyUsers = [
  {
    id: "user_1",
    name: "Motilal Rathod",
    email: "motilalrathod@gmail.com",
    image: profile_img_a,
    createdAt: "2026-01-12T00:00:00.000Z",
    updatedAt: "2026-01-12T00:00:00.000Z",
  },
  {
    id: "user_2",
    name: "Prajwal Kasture",
    email: "prajwal@example.com",
    image: profile_img_j,
    createdAt: "2026-01-12T00:00:00.000Z",
    updatedAt: "2026-01-12T00:00:00.000Z",
  },
  {
    id: "user_3",
    name: "Nilesh Sanap",
    email: "nilu111sanap@gmail.com",
    image: profile_img_o,
    createdAt: "2026-01-12T00:00:00.000Z",
    updatedAt: "2026-01-12T00:00:00.000Z",
  },
];

export const dummyWorkspaces = [
  {
    id: "org_1",
    name: "College Projects Workspace",
    slug: "college-projects-workspace",
    description: "Workspace for college academic projects and team-based learning.",
    settings: {},
    ownerId: "user_3",
    createdAt: "2026-01-12T00:00:00.000Z",
    image_url: workspace_img_default,
    updatedAt: "2026-01-12T00:00:00.000Z",
    members: [
      {
        id: "a7422a50-7dfb-4e34-989c-881481250f0e",
        userId: "user_1",
        workspaceId: "org_1",
        message: "",
        role: "ADMIN",
        user: dummyUsers[0],
      },
      {
        id: "b325ed10-00d8-4e22-b94d-33a9994fd06b",
        userId: "user_2",
        workspaceId: "org_1",
        message: "",
        role: "ADMIN",
        user: dummyUsers[1],
      },
      {
        id: "0f786ac0-62f7-493f-a5a0-787fd7c9c8b3",
        userId: "user_3",
        workspaceId: "org_1",
        message: "",
        role: "ADMIN",
        user: dummyUsers[2],
      },
    ],
    projects: [
      {
        id: "proj_codeclub_1",
        name: "CodeClub Platform",
        description:
          "A student community platform where members can share coding resources, events, and project ideas.",
        priority: "HIGH",
        status: "ACTIVE",
        start_date: "2026-01-12T00:00:00.000Z",
        end_date: "2026-01-12T00:00:00.000Z",
        team_lead: "user_3",
        workspaceId: "org_1",
        progress: 70,
        createdAt: "2026-01-12T00:00:00.000Z",
        updatedAt: "2026-01-12T00:00:00.000Z",
        tasks: [
          {
            id: "task_codeclub_1",
            projectId: "proj_codeclub_1",
            title: "Design Homepage UI",
            description: "Create a clean and responsive homepage layout for the platform.",
            status: "IN_PROGRESS",
            type: "FEATURE",
            priority: "HIGH",
            assigneeId: "user_1",
            due_date: "2026-01-12T00:00:00.000Z",
            createdAt: "2026-01-12T00:00:00.000Z",
            updatedAt: "2026-01-12T00:00:00.000Z",
            assignee: dummyUsers[0],
            comments: [],
          },
          {
            id: "task_codeclub_2",
            projectId: "proj_codeclub_1",
            title: "Implement User Authentication",
            description: "Add login and signup functionality using simple form validation.",
            status: "TODO",
            type: "TASK",
            priority: "MEDIUM",
            assigneeId: "user_2",
            due_date: "2026-01-12T00:00:00.000Z",
            createdAt: "2026-01-12T00:00:00.000Z",
            updatedAt: "2026-01-12T00:00:00.000Z",
            assignee: dummyUsers[1],
            comments: [],
          },
          {
            id: "task_codeclub_3",
            projectId: "proj_codeclub_1",
            title: "Fix Navigation Bugs",
            description: "Resolve routing issues between dashboard and profile pages.",
            status: "TODO",
            type: "BUG",
            priority: "HIGH",
            assigneeId: "user_1",
            due_date: "2026-01-12T00:00:00.000Z",
            createdAt: "2026-01-12T00:00:00.000Z",
            updatedAt: "2026-01-12T00:00:00.000Z",
            assignee: dummyUsers[0],
            comments: [],
          },
        ],
        members: [
          {
            id: "mem_codeclub_1",
            userId: "user_1",
            projectId: "proj_codeclub_1",
            user: dummyUsers[0],
          },
          {
            id: "mem_codeclub_2",
            userId: "user_2",
            projectId: "proj_codeclub_1",
            user: dummyUsers[1],
          },
          {
            id: "mem_codeclub_3",
            userId: "user_3",
            projectId: "proj_codeclub_1",
            user: dummyUsers[2],
          },
        ],
      },
      {
        id: "proj_simonsays_1",
        name: "Simon Says Game",
        description:
          "A browser-based memory game where users repeat color sequences that grow progressively harder.",
        priority: "MEDIUM",
        status: "ACTIVE",
        start_date: "2026-01-12T00:00:00.000Z",
        end_date: "2026-01-12T00:00:00.000Z",
        team_lead: "user_3",
        workspaceId: "org_1",
        progress: 50,
        createdAt: "2026-01-12T00:00:00.000Z",
        updatedAt: "2026-01-12T00:00:00.000Z",
        tasks: [
          {
            id: "task_simonsays_1",
            projectId: "proj_simonsays_1",
            title: "Build Game Logic",
            description: "Implement sequence generation and user input validation.",
            status: "IN_PROGRESS",
            type: "FEATURE",
            priority: "HIGH",
            assigneeId: "user_1",
            due_date: "2026-01-12T00:00:00.000Z",
            createdAt: "2026-01-12T00:00:00.000Z",
            updatedAt: "2026-01-12T00:00:00.000Z",
            assignee: dummyUsers[0],
            comments: [],
          },
          {
            id: "task_simonsays_2",
            projectId: "proj_simonsays_1",
            title: "Add Sound Effects",
            description: "Attach unique sound to each button for better user experience.",
            status: "TODO",
            type: "IMPROVEMENT",
            priority: "MEDIUM",
            assigneeId: "user_2",
            due_date: "2026-01-12T00:00:00.000Z",
            createdAt: "2026-01-12T00:00:00.000Z",
            updatedAt: "2026-01-12T00:00:00.000Z",
            assignee: dummyUsers[1],
            comments: [],
          },
        ],
        members: [
          {
            id: "mem_simonsays_1",
            userId: "user_1",
            projectId: "proj_simonsays_1",
            user: dummyUsers[0],
          },
          {
            id: "mem_simonsays_2",
            userId: "user_2",
            projectId: "proj_simonsays_1",
            user: dummyUsers[1],
          },
          {
            id: "mem_simonsays_3",
            userId: "user_3",
            projectId: "proj_simonsays_1",
            user: dummyUsers[2],
          },
        ],
      },
    ],
    owner: dummyUsers[2],
  },
  {
    id: "org_2",
    name: "Personal Project Workspace",
    slug: "personal-project-workspace",
    description: "Workspace for personal learning projects and portfolio development.",
    settings: {},
    ownerId: "user_3",
    createdAt: "2026-01-12T00:00:00.000Z",
    image_url: workspace_img_default,
    updatedAt: "2026-01-12T00:00:00.000Z",
    members: [
      {
        id: "f5d37afc-c287-4bd8-a607-b50d20837234",
        userId: "user_3",
        workspaceId: "org_2",
        message: "",
        role: "ADMIN",
        user: dummyUsers[2],
      },
      {
        id: "f5c04fe5-a0f5-4d34-bcf6-ea54dce1b546",
        userId: "user_1",
        workspaceId: "org_2",
        message: "",
        role: "ADMIN",
        user: dummyUsers[0],
      },
      {
        id: "9b29463a-e828-4d4e-9d64-8e57a3ad1a90",
        userId: "user_2",
        workspaceId: "org_2",
        message: "",
        role: "ADMIN",
        user: dummyUsers[1],
      },
    ],
    projects: [
      {
        id: "proj_airbnb_1",
        name: "Airbnb Clone",
        description:
          "A full-stack Airbnb-inspired platform with property listings, booking flow, and user authentication.",
        priority: "HIGH",
        status: "ACTIVE",
        start_date: "2026-01-12T00:00:00.000Z",
        end_date: "2026-01-12T00:00:00.000Z",
        team_lead: "user_3",
        workspaceId: "org_2",
        progress: 80,
        createdAt: "2026-01-12T00:00:00.000Z",
        updatedAt: "2026-01-12T00:00:00.000Z",
        tasks: [
          {
            id: "task_airbnb_1",
            projectId: "proj_airbnb_1",
            title: "Build Listing Pages",
            description: "Design and implement property listing cards and detail pages.",
            status: "IN_PROGRESS",
            type: "FEATURE",
            priority: "HIGH",
            assigneeId: "user_1",
            due_date: "2026-01-12T00:00:00.000Z",
            createdAt: "2026-01-12T00:00:00.000Z",
            updatedAt: "2026-01-12T00:00:00.000Z",
            assignee: dummyUsers[0],
            comments: [],
          },
          {
            id: "task_airbnb_2",
            projectId: "proj_airbnb_1",
            title: "Implement Booking Flow",
            description: "Create date selection, pricing calculation, and booking confirmation flow.",
            status: "TODO",
            type: "TASK",
            priority: "MEDIUM",
            assigneeId: "user_2",
            due_date: "2026-01-12T00:00:00.000Z",
            createdAt: "2026-01-12T00:00:00.000Z",
            updatedAt: "2026-01-12T00:00:00.000Z",
            assignee: dummyUsers[1],
            comments: [],
          },
          {
            id: "task_airbnb_3",
            projectId: "proj_airbnb_1",
            title: "Fix Image Upload Bug",
            description: "Resolve issues with uploading and displaying property images.",
            status: "TODO",
            type: "BUG",
            priority: "HIGH",
            assigneeId: "user_1",
            due_date: "2026-01-12T00:00:00.000Z",
            createdAt: "2026-01-12T00:00:00.000Z",
            updatedAt: "2026-01-12T00:00:00.000Z",
            assignee: dummyUsers[0],
            comments: [],
          },
        ],
        members: [
          {
            id: "mem_airbnb_1",
            userId: "user_3",
            projectId: "proj_airbnb_1",
            user: dummyUsers[2],
          },
          {
            id: "mem_airbnb_2",
            userId: "user_1",
            projectId: "proj_airbnb_1",
            user: dummyUsers[0],
          },
          {
            id: "mem_airbnb_3",
            userId: "user_2",
            projectId: "proj_airbnb_1",
            user: dummyUsers[1],
          },
        ],
      },
      {
        id: "proj_chainstock_1",
        name: "ChainStock Analysis",
        description:
          "An automation testing framework using Selenium and Playwright for regression and performance testing.",
        priority: "MEDIUM",
        status: "ACTIVE",
        start_date: "2026-01-12T00:00:00.000Z",
        end_date: "2026-01-12T00:00:00.000Z",
        team_lead: "user_3",
        workspaceId: "org_2",
        progress: 60,
        createdAt: "2026-01-12T00:00:00.000Z",
        updatedAt: "2026-01-12T00:00:00.000Z",
        tasks: [
          {
            id: "task_chainstock_1",
            projectId: "proj_chainstock_1",
            title: "Migrate to Latest Playwright",
            description: "Upgrade test scripts to the latest Playwright version.",
            status: "IN_PROGRESS",
            type: "IMPROVEMENT",
            priority: "HIGH",
            assigneeId: "user_1",
            due_date: "2026-01-12T00:00:00.000Z",
            createdAt: "2026-01-12T00:00:00.000Z",
            updatedAt: "2026-01-12T00:00:00.000Z",
            assignee: dummyUsers[0],
            comments: [],
          },
          {
            id: "task_chainstock_2",
            projectId: "proj_chainstock_1",
            title: "Enable Parallel Test Execution",
            description: "Configure CI pipelines to run tests concurrently.",
            status: "TODO",
            type: "TASK",
            priority: "MEDIUM",
            assigneeId: "user_2",
            due_date: "2026-01-12T00:00:00.000Z",
            createdAt: "2026-01-12T00:00:00.000Z",
            updatedAt: "2026-01-12T00:00:00.000Z",
            assignee: dummyUsers[1],
            comments: [],
          },
          {
            id: "task_chainstock_3",
            projectId: "proj_chainstock_1",
            title: "Add Visual Regression Testing",
            description: "Implement screenshot comparison for UI regression detection.",
            status: "TODO",
            type: "FEATURE",
            priority: "LOW",
            assigneeId: "user_1",
            due_date: "2026-01-12T00:00:00.000Z",
            createdAt: "2026-01-12T00:00:00.000Z",
            updatedAt: "2026-01-12T00:00:00.000Z",
            assignee: dummyUsers[0],
            comments: [],
          },
        ],
        members: [
          {
            id: "mem_chainstock_1",
            userId: "user_3",
            projectId: "proj_chainstock_1",
            user: dummyUsers[2],
          },
          {
            id: "mem_chainstock_2",
            userId: "user_1",
            projectId: "proj_chainstock_1",
            user: dummyUsers[0],
          },
          {
            id: "mem_chainstock_3",
            userId: "user_2",
            projectId: "proj_chainstock_1",
            user: dummyUsers[1],
          },
        ],
      },
    ],
    owner: dummyUsers[2],
  },
];
